# Core models
models:
  script_model: gpt-5

# Per-account settings (selected via TOPIC env)
accounts:
  math:
    script_prompt: >-
      Write a fast-paced, witty 2-character dialogue between Peter and Stewie about a math concept.
      120-160 words, punchy back-and-forth, playful jabs, simple analogies, one clear takeaway,
      and end with a hook to learn more.
    characters:
      - id: peter_griffin
        name: Peter
      - id: stewie_griffin
        name: Stewie
